version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: workwise_db
      POSTGRES_USER: workwise_user
      POSTGRES_PASSWORD: asd123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d  # Initialization scripts for setting up the DB
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    image: workwise-web:latest   # Use the pre-built image
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/app
      - ./logs:/app/logs
    environment:
      DATABASE_NAME: workwise_db
      DATABASE_USER: workwise_user
      DATABASE_PASSWORD: asd123
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      replicas: 1                   # Set the desired number of replicas
      restart_policy:
        condition: on-failure

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"                     # Exposes host port 80 for incoming traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom NGINX configuration
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
