name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t workwise-web:latest -f web/Dockerfile web/

      - name: Start DB service using Docker Compose
        run: docker compose -f docker-compose.yml up -d db

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres service..."
          sleep 15

      - name: Run Django migrations
        run: docker compose -f docker-compose.yml run --rm web python manage.py migrate

      - name: Run Django tests
        run: docker compose -f docker-compose.yml run --rm web python manage.py test

      - name: Tear down services
        run: docker compose -f docker-compose.yml down
